<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comparisons [
  <!ELEMENT comparisons (hotel*)>
  <!ELEMENT hotel (num,name,stars,reviews,score)>
  <!ELEMENT num (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT stars (#PCDATA)>
  <!ELEMENT reviews (#PCDATA)>
  <!ELEMENT score (#PCDATA)>
  <!ATTLIST comparisons date CDATA #REQUIRED>
  <!ATTLIST comparisons location CDATA #REQUIRED>
  <!ATTLIST comparisons company CDATA #REQUIRED>
  <!ATTLIST comparisons url CDATA #REQUIRED>
]>
<comparisons date="2021-02-25" location="Wollongong" company="Hotels Combined" url="https://www.hotelscombined.com.au">
   <hotel>
     <num>1</num>
      <name>Novotel Wollongong Northbeach</name>
      <stars>4</stars>
      <reviews>3123</reviews>
      <score>8.1</score>
   </hotel>
   <hotel>
      <num>2</num>
      <name>Sage Hotel Wollongong</name>
      <stars>4</stars>
      <reviews>3802</reviews>
      <score>7.8</score>
   </hotel>
   <hotel>
     <num>3</num>
      <name>Adina Apartment Hotel Wollongong</name>
      <stars>4</stars>
      <reviews>1046</reviews>
      <score>8.7</score>
   </hotel>
   <hotel>
     <num>4</num>
      <name>Quality Suites Pioneer Sands</name>
      <stars>4</stars>
      <reviews>656</reviews>
      <score>8.6</score>
   </hotel>
   <hotel>
     <num>5</num>
      <name>Mantra Wollongong</name>
      <stars>4</stars>
      <reviews>1052</reviews>
      <score>7.6</score>
   </hotel>
   <hotel>
     <num>6</num>
      <name>The Belmore All-Suite Hotel</name>
      <stars>3</stars>
      <reviews>1214</reviews>
      <score>8.8</score>
   </hotel>
   <hotel>
     <num>7</num>
      <name>Boat Harbour Motel</name>
      <stars>3</stars>
      <reviews>869</reviews>
      <score>8.0</score>
   </hotel>
   <hotel>
     <num>8</num>
      <name>Solomon Inn Wollongong</name>
      <stars>3</stars>
      <reviews>731</reviews>
      <score>7.3</score>
   </hotel>
   <hotel>
     <num>9</num>
      <name>Best Western City Sands</name>
      <stars>4</stars>
      <reviews>1219</reviews>
      <score>8.3</score>
   </hotel>
   <hotel>
     <num>10</num>
      <name>Flinders Motel</name>
      <stars>3</stars>
      <reviews>701</reviews>
      <score>7.4</score>
   </hotel>
</comparisons>
